### PR TITLE
Protect the Dashboard from Pods

### PR DESCRIPTION
**Pull request by bgeesaman**
Signed-off-by: Brad Geesaman <bradgeesaman+github@gmail.com>

### CODE REVIEW

**Comment by bgeesaman** [comment]
```kubectl proxy``` works as expected with this in place, but connecting directly to the dashboard from regular pods is blocked.  Because the dashboard has a full permission token mounted, this prevents a path to full cluster escalation/compromise.

**Comment by chuckha** [comment]
@bgeesaman looks like you probably force pushed a commit without a sign-off

**Comment by chuckha** [comment]
ok to test

**Comment by bgeesaman** [comment]
Yeah, I forgot to place it in a commit vs in the PR text.  My apologies.  We can close this and I can do a fresh one if you like.

**Comment by chuckha** [comment]
@bgeesaman whatever is easiest for you :) Thanks for the fix on this one!

**Pull request closed without merging**
