### PR TITLE
Update S3 parameters to prod locations

### PR DESCRIPTION
**Pull request by kensimon**
Templates are live in the quickstart-reference bucket under
heptio/latest.

Signed-off-by: Ken Simon <ninkendo@gmail.com>

### CODE REVIEW

**Comment by kensimon** [comment]
@avattathil @bchav Looking for your guidance here... is this necessary?  I notice when I deploy with https://s3.amazonaws.com/quickstart-reference/heptio/latest/templates/kubernetes-cluster-with-new-vpc.template it already is preconfigured to use the correct S3 parameters.  Is that part of your CI process?  If so, is it worth us updating our own template?

**Comment by avattathil** [comment]
Yes, I would update your side with those key prefixes.  (You can probably
do another fast forward like you did last time to sync the previous
changes). The way I have CI currently setup is pointing to the test S3
bucket and overriding the default values in the template using the json
input. This way I can test the latest update prior to making any changes to
prod. Once it tests clean, ci promote the changes to master and copy the
exact content from our forks master to S3.

I was actually going to send you a note about this today. Let me know if
the above makes sense. Happy to clarify anything that might be unclear.

Thanks
--Tony

**Comment by kensimon** [comment]
Ah, I didn't see that you had added more commits since I last synced.  I assume this is the last of the commits made in the aws fork?  (Typically commits will start with our repo, no?)

I went ahead and fast-fowarded our master to your develop branch, so they're in sync again.  Closing this.

**Comment by avattathil** [comment]
Yep, going forward any template related commits will come to the upstream
(your repo).

The only thing we may update locally are the contents in the ci folder
which should be static anyway going forward.

Thanks
--Tony

On Feb 28, 2017 4:37 PM, "Ken Simon" <notifications@github.com> wrote:

Ah, I didn't see that you had added more commits since I last synced. I
assume this is the last of the commits made in the aws fork? (Typically
commits will start with our repo, no?)

I went ahead and fast-fowarded our master to your develop branch, so
they're in sync again. Closing this.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/heptio/aws-quickstart/pull/38#issuecomment-283207367>,
or mute the thread

**Pull request closed without merging**
