### PR TITLE
Bump to latest release of weave, fix documentation links

### PR DESCRIPTION
**Pull request by errordeveloper**

### CODE REVIEW

**Comment by jbeda** [comment]
Look great @errordeveloper.  Can you put in the DCO sign off as outlined in https://github.com/heptio/aws-quickstart/blob/master/CONTRIBUTING.md?

Also -- be aware that we are going to do releases that get pushed through the official AWS quickstart on a regular schedule so this'll get picked up on the next one there.

**Comment by errordeveloper** [comment]
Joe, qq - how do we get link in the PDF doc updated?

**Comment by errordeveloper** [comment]
Commit signed-off now.

**Comment by jbeda** [comment]
We are still figuring out how we do updates here.  Getting the PDF updated may be a bit trickier.  Give us a bit and we'll batch up requests with the amazon folks so they don't get annoyed with us :)

**Pull request merged**
