### PR TITLE
Default instance type to m5.large

### PR DESCRIPTION
**Pull request by matthewfischer**
m5 should be cheaper in all regions and offers better performance as well.

### CODE REVIEW

**Comment by matthewfischer** [comment]
Unsure why but the master fails to create using m5.large - so for now, bailing on this

**Comment by detiber** [comment]
Odd, I had tested with m5 instance types roughly 1 year ago or so, but ended up deferring then because they were not available in many regions at that point. @johnSchnake any ideas on why m5 instances wouldn't work with the current state?

**Comment by matthewfischer** [comment]
The stack failed to create (master node failed to create) and as my goal
was using it, I didn't debug. I tried several times. I don't know why it
shouldn't work.

**Comment by johnSchnake** [comment]
No idea why something like that would fail; I'll try it out and see what the errors indicate. AWS did push/publicize that m5 was just _better_ than m4 and even just reading the base stats/price it does seem to be a better choice. https://aws.amazon.com/blogs/aws/m5-the-next-generation-of-general-purpose-ec2-instances/

**Comment by johnSchnake** [comment]
No idea why something like that would fail; I'll try it out and see what the errors indicate. AWS did push/publicize that m5 was just _better_ than m4 and even just reading the base stats/price it does seem to be a better choice. https://aws.amazon.com/blogs/aws/m5-the-next-generation-of-general-purpose-ec2-instances/

**Comment by matthewfischer** [comment]
I'll try it again right now and see if I can get a more useful error from cfn.

**Comment by johnSchnake** [comment]
I made these changes locally and did the boot-from-local script and everything went fine. 
image

@matthewfischer let me know what the error is you get; otherwise I say we can reopen this and move it forward.

I did also (locally) change the other template though to use `m5.large` as well; the other `...with_new_vpc.template` template passes its instanceType parameter to the cluster template. So I think you'd still end up with m4 if only this one line was changed.

**Comment by matthewfischer** [comment]
It also worked for me just now. I'm willing to chalk it up to me making another mistake. But I have an m5 based cluster up and running.

**Comment by johnSchnake** [comment]
@matthewfischer glad that it is working for both of us now.

I do think you needed to adjust both templates though. Once that is done and you sign your commit then I can merge.

Thanks!

**Comment by johnSchnake** [comment]
Closing based on #261 which marks this repo as deprecated and no longer under development.

**Pull request closed without merging**
