### PR TITLE
Added parameter for internal or internet-facing ELB

### PR DESCRIPTION
**Pull request by danhartfiction**
This is the pull request I wrote for Issue #91:
https://github.com/heptio/aws-quickstart/issues/91

### CODE REVIEW

**Comment by chuckha** [comment]
@danhartfiction This is missing a sign-off, please sign off your commits using `git commit --signoff` or `git commit -s`

**Comment by danhartfiction** [comment]
I think I've successfully signed off on the new commit (which also updates the Description field to read more like the others.)

My git-fu isn't the best, so if there's a process I could follow to make this conform better please let me know!

**Comment by chuckha** [comment]
@danhartfiction You've got to sign off all commits, so if you squash these down then we will be good to go! Thanks so much for the contribution

**Comment by chuckha** [comment]
I'm going to grab the diff from the first commit and then use your second commit as is that you signed off. I will add attribution in the commit log for the first commit. We are releasing this tomorrow and need all the patches merged today. Thanks you for the contribution!

**Comment by chuckha** [comment]
Closed in favor of #100

**Pull request closed without merging**
